"""
services/email_service.py
Sends department summary emails via SendGrid.
Falls back to a console log if SendGrid is not configured (demo mode).
"""

import logging
from datetime import datetime
from typing import List

from config.settings import settings
from services.database import (
    get_unsummarised_queries,
    mark_queries_emailed,
    log_email,
)
from services.ai_agent import generate_department_summary

logger = logging.getLogger(__name__)

DEPARTMENT_CONFIG = {
    "product": {
        "name": "Product Team",
        "email": settings.email.product_dept_email,
        "emoji": "📦",
    },
    "payment": {
        "name": "Payments Team",
        "email": settings.email.payment_dept_email,
        "emoji": "💳",
    },
}


def _html_template(department_name: str, summary_text: str, query_count: int, date_str: str) -> str:
    """Wrap plain-text summary in a clean HTML email."""
    # Convert newlines to <br> and basic markdown-style headers
    lines = []
    for line in summary_text.split("\n"):
        line = line.strip()
        if not line:
            lines.append("<br>")
        elif line.startswith("# "):
            lines.append(f"<h2 style='color:#1a56db'>{line[2:]}</h2>")
        elif line.startswith("## "):
            lines.append(f"<h3 style='color:#374151'>{line[3:]}</h3>")
        elif line.startswith("- ") or line.startswith("• "):
            lines.append(f"<li style='margin:4px 0'>{line[2:]}</li>")
        else:
            lines.append(f"<p style='margin:6px 0'>{line}</p>")

    body_html = "\n".join(lines)

    return f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f9fafb; margin: 0; padding: 0; }}
    .container {{ max-width: 640px; margin: 32px auto; background: #fff; border-radius: 12px;
                  box-shadow: 0 2px 12px rgba(0,0,0,0.08); overflow: hidden; }}
    .header {{ background: linear-gradient(135deg, #1a56db 0%, #0e3fa3 100%);
               color: white; padding: 28px 32px; }}
    .header h1 {{ margin: 0; font-size: 22px; font-weight: 700; }}
    .header p {{ margin: 6px 0 0; opacity: 0.85; font-size: 14px; }}
    .badge {{ display: inline-block; background: rgba(255,255,255,0.2);
              border-radius: 20px; padding: 4px 14px; font-size: 13px; margin-top: 10px; }}
    .body {{ padding: 28px 32px; color: #374151; font-size: 15px; line-height: 1.6; }}
    .footer {{ background: #f3f4f6; padding: 16px 32px; font-size: 12px; color: #9ca3af; }}
    ul {{ padding-left: 20px; }}
    li {{ margin: 4px 0; }}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📊 Daily Query Summary — {department_name}</h1>
      <p>{date_str}</p>
      <span class="badge">{query_count} queries processed</span>
    </div>
    <div class="body">
      {body_html}
    </div>
    <div class="footer">
      This summary was auto-generated by the AI Voice Agent system.<br>
      Powered by {settings.company_name} · {date_str}
    </div>
  </div>
</body>
</html>
"""


def _send_via_sendgrid(to_email: str, subject: str, html_body: str) -> bool:
    """Send email via SendGrid. Returns True on success."""
    if not settings.email.sendgrid_api_key:
        logger.warning("SENDGRID_API_KEY not set. Printing email to console instead.")
        print(f"\n{'='*60}\nEMAIL (console fallback)\nTo: {to_email}\nSubject: {subject}\n{'='*60}")
        print(html_body[:500], "...[truncated]")
        return True  # treat as success for demo

    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail

        message = Mail(
            from_email=(settings.email.from_email, settings.email.from_name),
            to_emails=to_email,
            subject=subject,
            html_content=html_body,
        )
        sg = SendGridAPIClient(settings.email.sendgrid_api_key)
        response = sg.send(message)
        logger.info("Email sent to %s — status %s", to_email, response.status_code)
        return response.status_code in (200, 202)
    except Exception as exc:
        logger.error("SendGrid error: %s", exc)
        return False


def send_department_summaries() -> dict:
    """
    Main scheduled job:
    1. Fetch new queries per department
    2. Generate AI summary
    3. Send email
    4. Mark queries as emailed
    Returns a results dict for monitoring.
    """
    results = {}
    date_str = datetime.utcnow().strftime("%B %d, %Y")

    for dept_key, dept_info in DEPARTMENT_CONFIG.items():
        queries = get_unsummarised_queries(category=dept_key)
        query_dicts = [q.to_dict() for q in queries]
        query_ids = [q.id for q in queries]

        if not query_dicts:
            logger.info("No new %s queries — skipping email.", dept_key)
            results[dept_key] = {"sent": False, "reason": "no_queries", "count": 0}
            continue

        logger.info("Generating summary for %d %s queries...", len(query_dicts), dept_key)
        try:
            summary = generate_department_summary(query_dicts, dept_key)
        except Exception as exc:
            logger.error("Failed to generate summary for %s: %s", dept_key, exc)
            results[dept_key] = {"sent": False, "reason": "ai_error", "count": len(query_dicts)}
            continue

        subject = f"{dept_info['emoji']} {dept_info['name']} Daily Query Summary — {date_str}"
        html_body = _html_template(dept_info["name"], summary, len(query_dicts), date_str)

        success = _send_via_sendgrid(dept_info["email"], subject, html_body)

        log_email(
            department=dept_key,
            recipient=dept_info["email"],
            query_count=len(query_dicts),
            summary=summary,
            success=success,
        )

        if success:
            mark_queries_emailed(query_ids)

        results[dept_key] = {
            "sent": success,
            "count": len(query_dicts),
            "recipient": dept_info["email"],
        }

    return results
